version: '3.8'

services:
  # Frontend service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - database

  # Database service (if needed)
  database:
    image: postgres:13
    environment:
      POSTGRES_USER: ivolex_user
      POSTGRES_PASSWORD: ivolex_password
      POSTGRES_DB: ivolex_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/var/www/ivolex
    depends_on:
      - frontend

volumes:
  postgres_data:
