// Main pages index - exports all screens for easy importing
export { default as Home } from './screens/Home'
export { default as Category } from './screens/Category'
export { default as Product } from './screens/Product'
export { default as Cart } from './screens/Cart'
export { default as Checkout } from './screens/Checkout'
export { default as About } from './screens/About'
export { default as Contact } from './screens/Contact'
export { default as Login } from './screens/Login'
export { default as Register } from './screens/Register'
export { default as Profile } from './screens/Profile'
export { default as Shop } from './screens/Shop'
export { default as OrderConfirmation } from './screens/OrderConfirmation'
export { default as NotFound } from './screens/NotFound'